server:
  port: 8010

spring:
  application:
    name: movie-service

userservice:
  url: http://192.168.63.192:8000/

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG