server:
  port: 9411

spring:
  application:
    name: zipkin-service
  rabbitmq:
    host: 192.168.37.171
    port: 5672
    username: admin
    password: xilife
    virtual-host: xdpitc
    queue: zipkin
